---
downloads: ~/.ansible-downloads/

configure_sudoers: yes
configure_terminal: yes
configure_osx: yes
configure_vim: yes

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitconfig
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - autoconf
  - bash-completion
  - chromedriver
  # - doxygen
  - gettext
  - gifsicle
  - git
  - gpg
  - httpie
  - hub
  - iperf
  - libevent
  - sqlite
  - mas
  - mcrypt
  - nmap
  - npm
  - nvm
  - openssl
  - pv
  - readline
  - ssh-copy-id
  - tree
  - wget
  - wrk

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/php
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # - docker
  - dropbox
  - duet
  - evernote
  - firefox
  - google-chrome
  - google-drive
  - handbrake
  - jumpcut
  - licecap
  - macvim
  - nvalt
  - phpstorm
  - pixelmator
  - sequel-pro
  - skitch
  # - slack
  - spotify
  # - sublime-text
  - telegram
  - toggldesktop
  - transmission
  - vagrant
  - virtualbox
  - vlc

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 441258766, name="Magnet" }
  - { id: 407963104, name="Pixelmator" }
  - { id: 405580712, name="StuffIt Expander" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"
